// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv3hUQZeCbahNSYNRGJk3bJ1UEDrIb-rs',
    appId: '1:543798250912:web:68e12fa91f6f2d1f1e68c5',
    messagingSenderId: '543798250912',
    projectId: 'health-monitor-system-3cb09',
    authDomain: 'health-monitor-system-3cb09.firebaseapp.com',
    storageBucket: 'health-monitor-system-3cb09.appspot.com',
    databaseURL: 'https://health-monitor-system-3cb09-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC44D7BxZtfefp3MirCNr35p5_zeByeycU',
    appId: '1:543798250912:android:3920d0d06356d47c1e68c5',
    messagingSenderId: '543798250912',
    projectId: 'health-monitor-system-3cb09',
    storageBucket: 'health-monitor-system-3cb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtpUNg65azID-nmWmaDxlSnV3CaPJs64',
    appId: '1:543798250912:ios:f902162e58b2550f1e68c5',
    messagingSenderId: '543798250912',
    projectId: 'health-monitor-system-3cb09',
    storageBucket: 'health-monitor-system-3cb09.appspot.com',
    iosClientId: '543798250912-ls8pcpaufla7m4hrmn7qlvthlit5fps4.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitorSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrtpUNg65azID-nmWmaDxlSnV3CaPJs64',
    appId: '1:543798250912:ios:f902162e58b2550f1e68c5',
    messagingSenderId: '543798250912',
    projectId: 'health-monitor-system-3cb09',
    storageBucket: 'health-monitor-system-3cb09.appspot.com',
    iosClientId: '543798250912-ls8pcpaufla7m4hrmn7qlvthlit5fps4.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitorSystem',
  );
}
